#!/bin/bash


inotifywait -q -m -r -e moved_to --format "%e %w%f" $1 |
  while read evt filepath ; do
    if [[ $filepath == *"yaml" ]]; then        
        microk8s.kubectl apply -f $filepath
    fi
    
done >/dev/null 2>&1 &
